import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabase } from '@/app/lib/supabase/server';
import { STORAGE_BUCKET, listFiles } from '@/app/lib/spaces/storage';
import { ensureManifest, readManifest, writeManifest } from '@/app/lib/spaces/manifest';
import { normalizeSegment, resolveSpacePrefix } from '@/app/lib/spaces/paths';

export async function PATCH(req: NextRequest, { params }: { params: { name: string } }) {
  let userId: string | undefined;
  const currentRawName = params.name;
  let normalizedCurrentName: string | undefined;
  let normalizedNewName: string | undefined;
  try {
    const supabase = await createServerSupabase();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: { code: 'UNAUTHORIZED', message: 'Unauthorized' } }, { status: 401 });
    }
    userId = user.id;
    normalizedCurrentName = normalizeSegment(currentRawName);

    const body = await req.json().catch(() => null);
    const rawNewName = body?.newName;
    if (!rawNewName || typeof rawNewName !== 'string') {
      return NextResponse.json({ error: { code: 'INVALID_REQUEST', message: "Missing or invalid 'newName'" } }, { status: 400 });
    }
    normalizedNewName = normalizeSegment(rawNewName);

    if (normalizedCurrentName === normalizedNewName) {
      return NextResponse.json({ error: { code: 'NO_OP', message: 'New name matches existing name' } }, { status: 400 });
    }

    // Ensure destination does not already exist
    const existingDest = await readManifest(userId, normalizedNewName);
    if (existingDest) {
      return NextResponse.json({ error: { code: 'ALREADY_EXISTS', message: 'A space with that name already exists' } }, { status: 409 });
    }

    const sourcePrefix = resolveSpacePrefix(userId, normalizedCurrentName);
    const destinationPrefix = resolveSpacePrefix(userId, normalizedNewName);

    // Ensure manifest/source exists before proceeding
    const existingManifest = await readManifest(userId, normalizedCurrentName);
    if (!existingManifest) {
      return NextResponse.json({ error: { code: 'NOT_FOUND', message: 'Space not found' } }, { status: 404 });
    }

    // List all files (recursive) and move to new prefix
    const files = await listFiles(sourcePrefix, { recursive: true });
    for (const file of files) {
      if (file.isDirectory) continue;
      const fromPath = sourcePrefix + file.path;
      const toPath = destinationPrefix + file.path;
      const { error: moveError } = await supabase.storage.from(STORAGE_BUCKET).move(fromPath, toPath);
      if (moveError) {
        console.error('[PATCH /api/spaces/[name]] move failed', { fromPath, toPath, moveError });
        const status = (moveError as any)?.status || 500;
        const code = moveError.name || 'MOVE_FAILED';
        return NextResponse.json({ error: { code, message: moveError.message } }, { status });
      }
    }

    // Write updated manifest with new name and clear auto-generated flag
    const updatedManifest = {
      ...existingManifest,
      name: rawNewName,
      last_updated_at: new Date().toISOString(),
      is_name_auto_generated: false,
    };
    await writeManifest(userId, normalizedNewName, updatedManifest);

    // Ensure manifest exists for destination directory to avoid race conditions
    await ensureManifest(userId, normalizedNewName, {
      nameOverride: rawNewName,
      isNameAutoGenerated: false,
      createdAt: existingManifest.created_at,
      lastUpdatedAt: updatedManifest.last_updated_at,
    });

    return NextResponse.json({ renamed: true, manifest: updatedManifest }, { status: 200 });
  } catch (err: any) {
    console.error('[PATCH /api/spaces/[name]] error', {
      userId,
      from: normalizedCurrentName,
      to: normalizedNewName,
      name: err?.name,
      code: err?.code,
      status: err?.status,
      message: err?.message,
      stack: err?.stack,
    });
    const status = err?.status || 500;
    const code = err?.code || err?.name || 'INTERNAL_ERROR';
    return NextResponse.json({ error: { code, message: err?.message || 'Internal Error' } }, { status });
  }
}
